[package]
name = "dilobo"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
toml = "0.2.1"
rustc-serialize = "0.3.22"
discord = { git = "https://github.com/oberien/discord-rs" }
strfmt = "0.1.5"
