[bot]
# bot token
token = "foobar"

[[server]]
# To identify the server you can specify server_name or server_id.
# If both are given, they'll be checked against each other.
server_name = "My Awesome Server"
# server_id = 1337

# To identify the channel to log into you can specify log_channel_name or
# log_channel_id. If both are given, they'll be checked against each other.
log_channel_name = "log"
# log_channel_id = 42
verbose = false

# Messages
message_create_msg = "**New message** from `{author_name}#{author_discriminator}` in <#{channel_id}> at {time}: `{content}`"
message_delete_cached_msg = "**Message deleted** from `{author_name}#{author_discriminator}` in <#{channel_id}>: `{content}`"
message_delete_uncached_msg = "**Message deleted** (id: `{message_id}`) in <#{channel_id}>"
message_delete_bulk_msg = "**{count} messages deleted** in <#{channel_id}>"
server_member_add_msg = "New **{type} joined**: <@{id}> (`{name}#{discriminator}`) at {time} with nick `{nick}`. Roles: {roles}, Mute: {mute}, Deaf: {deaf}"
server_member_role_add_msg = "**Role** `{role_name}` **added** to `{member_name}#{member_discriminator}`"
server_member_role_remove_msg = "**Role** `{role_name}` **removed** from `{member_name}#{member_discriminator}`"
server_member_nick_change_msg = "`{member_name}#{member_discriminator}` changed **nick** from `{from}` to `{to}`"
server_member_no_change_msg = "`{member_name}#{member_discriminator}` changed but **no difference**"
server_member_remove_msg = "**{Type} left**: <@{id}> ({name}#{discriminator})"
server_role_create_msg = "**Role** `{name}` **created** with permissions {perms}"
server_ban_add_msg = "**{Type} banned**: <@{id}> ({name}#{discriminator})"
server_ban_remove_msg = "**{Type} UNbanned**: <@{id}> ({name}#{discriminator})"
server_emoji_add_msg = "**Emoji** `{emoji_name}` **added**"
server_emoji_remove_msg = "**Emoji** `{emoji_name}` **removed**"
server_emoji_name_change_msg = "**Emoji name** changed from `{from}` to `{to}`"
channel_create_msg = "**{Type}channel** <#{id}> ({name}) **created** with permissions {perms}"
channel_update_no_change_msg = "**Channel** <#{channel_id}> ({channel_name}) changed but **no difference**"
channel_update_name_msg = "**Channel** <#{channel_id}> changed **name** from `{from}` to `{to}`"
channel_update_user_perms_msg = "**Channel** <#{channel_id}> (`{channel_name}`) changed **permission** `{permission}` for user <@{user_id}> from `{from}` to `{to}`"
channel_update_role_perms_msg = "**Channel** <#{channel_id}> (`{channel_name}`) changed **permission** `{permission}` for role <@&{role_id}> from `{from}` to `{to}`"
channel_update_topic_msg = "**Channel** <#{channel_id}> (`{channel_name}`) changed **topic** from `{from}` to `{to}`"
channel_update_position_msg = "**Channel** <#{channel_id}> (`{channel_name}`) changed **position** from `{from}` to `{to}`"
channel_update_bitrate_msg = "**Channel** <#{channel_id}> (`{channel_name}`) changed **bitrate** from `{from}` to `{to}`"
channel_update_user_limit_msg = "**Channel** <#{channel_id}> ({channel_name}) changed **user limit** from `{from}` to `{to}`"
channel_delete_msg = "**{Type}channel** #{name} **deleted**"
reaction_add_cached_msg = "**Reaction** by `{user_name}#{user_discriminator}` with :{emoji_name}: in <#{channel_id}> to message `{message_content}` from `{message_author_name}#{message_author_discriminator}`"
reaction_add_uncached_msg = "**Reaction** by `{user_name}#{user_discriminator}` with :{emoji_name}: in <#{channel_id}> to message `{message_id}`"
reaction_remove_cached_msg = "**Reaction removed** by `{user_name}#{user_discriminator}` with :{emoji_name}: in <#{channel_id}> to message `{message_content}` from `{message_author_name}#{message_author_discriminator}`"
reaction_remove_uncached_msg = "**Reaction removed** by `{user_name}#{user_discriminator}` with :{emoji_name}: in <#{channel_id}> to message `{message_id}`"
message_update_uncached_msg = "**Message edited** (uncached) `{id}` in <#{channel_id}> from `{author_name}#{author_discriminator}`"
message_update_kind_msg = "**Message Kind changed** of message in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` changed from `{from}` to `{to}`"
message_update_content_msg = "**Message** from `{cached_author_name}#{cached_author_discriminator}` **edited** from `{from}` to `{to}`"
message_update_nonce_msg = "**Message Nonce** of message in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` changed from `{from}` to `{to}`"
message_update_tts_msg = "**Message Text to Speach** changed of message in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` from `{from}` to `{to}`"
message_update_pinned_msg = "**Message pinned** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}`"
message_update_unpinned_msg = "**Message unpinned** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}`"
message_update_edited_time_msg = "**Message edit time** changed in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` from `{from}` to `{to}`"
message_update_mention_everyone_msg = "**Message mention everyone** changed in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` from `{from}` to `{to}`"
message_update_mention_added_msg = "**Message mention added** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` for `{name}#{discriminator}`"
message_update_mention_removed_msg = "**Message mention removed** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` for `{name}#{discriminator}`"
message_update_mention_role_added_msg = "**Message mention added** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` for <@&{id}>"
message_update_mention_role_removed_msg = "**Message mnetion removed** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` for <@&{id}>"
message_update_attachment_added_msg = "**Message added attachment** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` {url}"
message_update_attachment_removed_msg = "**Message removed attachment** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}` {url}"
message_update_embeds_added_msg = "**Message added embeds** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}`: {value}"
message_update_embeds_removed_msg = "**Message removed embeds** in <#{channel_id}> from `{cached_author_name}#{cached_author_discriminator}`: {value}"
