[bot]
# bot token
token = "foobar"

[[server]]
# To identify the server you can specify server_name or server_id.
# If both are given, they'll be checked against each other.
server_name = "My Awesome Server"
# server_id = 1337

# To identify the channel to log into you can specify log_channel_name or
# log_channel_id. If both are given, they'll be checked against each other.
log_channel_name = "log"
# log_channel_id = 42

# Messages
server_member_add_msg = "New {type} joined: <@{id}> ({name}#{discriminator}) at {time} with nick \"{nick}\". Roles: {roles}, Mute: {mute}, Deaf: {deaf}"
server_member_remove_msg = "{type} left: <@{id}> ({name}#{discriminator})"
